# Generated by Django 5.1.2 on 2024-10-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('method', models.CharField(choices=[('card', 'Кредитная карта'), ('cash', 'Оплата наличными')], max_length=4, verbose_name='Метод оплаты')),
                ('created_at', models.DateTimeField(verbose_name='Дата оплаты')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплата',
            },
        ),
    ]
