# Generated by Django 5.1.2 on 2024-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Дата оплаты'),
        ),
    ]
