# Generated by Django 5.1.2 on 2024-11-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=True, verbose_name='Статус рассылки')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет в случае ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания рассылки')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='materials.subscribe', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'рассылка обновления курса',
                'verbose_name_plural': 'рассылки обновления курса',
            },
        ),
    ]
