# Generated by Django 5.1.2 on 2024-11-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscribemailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribemailing',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='subscribemailing',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='materials.course', verbose_name='Курс рассылки'),
            preserve_default=False,
        ),
    ]
